global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: cancer-hospital-app
    metrics_path: /metrics
    static_configs:
      - targets:
          - app:7860

  - job_name: cancer-model-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - model-api:8001

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets:
          - cadvisor:8080
