apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cancer-hospital

resources:
  - namespace.yaml
  - app.yaml
  - model-api-external.yaml
  - prometheus.yaml
  - grafana.yaml
  - loki.yaml
  - promtail.yaml
  - cadvisor.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: cancer-hospital

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=config/prometheus.yml
  - name: loki-config
    files:
      - config.yml=config/loki-config.yml
  - name: promtail-config
    files:
      - config.yml=config/promtail-config.yml
  - name: grafana-datasources
    files:
      - datasources.yml=config/grafana-datasources.yml
  - name: grafana-dashboard-provider
    files:
      - dashboard-provider.yml=config/grafana-dashboard-provider.yml
  - name: grafana-dashboards
    files:
      - cancer-hospital-k8s-observability.json=config/cancer-hospital-k8s-observability.json

generatorOptions:
  disableNameSuffixHash: true
